### ISSUE TITLE
Could you update this to 3.39.0

### ISSUE THREAD

**Issue by Sultech** [flathub/no.mifi.losslesscut#12]
Could you update this to 3.39.0 I would really appreciate it

**Comment by muelli** [comment]
I'd love to, but we'd need to overcome the issues from https://github.com/flathub/no.mifi.losslesscut/pull/11

**Comment by mifi** [comment]
Hi! I just changed losslesscut so it no longer uses npm to download ffmpeg. You can now place ffmpeg and ffprobe binaries inside the directory ffmpeg/linux, and it will use those when packaging the app!

**Comment by muelli** [comment]
that sounds interesting!
Do you have an example to see how to it properly?

**Comment by mifi** [comment]
```bash
yarn

# Skip this step:
# yarn download-ffmpeg-linux
# Instead provide ffprobe and ffmpeg binaries
# e.g. from https://github.com/mifi/ffmpeg-builds/releases/download/4.4.1/ffmpeg-release-amd64-static.tar.xz
# then move them into the right place:
mkdir -p ./ffmpeg/linux
mv /path/to/ffprobe ./ffmpeg/linux/
mv /path/to/ffmpeg ./ffmpeg/linux/

# Then build
npx electron-builder --linux
```

this is the official github action build script:
https://github.com/mifi/lossless-cut/blob/master/.github/workflows/build.yml

**Comment by muelli** [comment]
I think I'm getting there.

My problem, though, is how to compile ffmpeg, s.t. losslesscut is happy:
```
/app/lossless-cut/resources/ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=1 -f null
Trailing options were found on the commandline.
Unknown input format: 'lavfi'
```
Do you happen to know the relevant configure flags?

Can I wish for a switch or something to disable ASAR? I couldn't find the electron-builder config. ASAR is compression and compression means we lose out on efficient updates.

**Comment by mifi** [comment]
I'm not sure about disabling asar. I know asar is being used because of its advantage off access files much faster than on a file system (maybe this is only true for windows which has slow file system access though).

Btw asar does not use compression

> Asar is a simple extensive archive format, it works like tar that concatenates all files together without compression, while having random access support.

https://github.com/electron/asar

If you really want to disable it I think there is some command line argument but I can't find it right now.

**Comment by mifi** [comment]
(and if not using asar there will be tens of thousands of files installed on the user's system because of `node_modules`)

**Comment by muelli** [comment]
I've patched ASAR out: https://github.com/flathub/no.mifi.losslesscut/pull/13/commits/f9eeb69e27594e8c3cfb1f6fae42931402e80606

**Comment by mifi** [comment]
Ok, note that it would be better to use the cli argument to electron-builder though, or you have to update your patch in the future if upstream package.json changes.
I believe it can be achieved with:
`electron-builder -c.asar=false` (not tested)

**Comment by muelli** [comment]
thanks for the pointer :)
Currently, the "pack-linux" shorthand is used: https://github.com/flathub/no.mifi.losslesscut/blob/791f47bf9f82f141f52f8e23f2b2333a81dd25b4/no.mifi.losslesscut.yaml#L69

but that seems to simply translate to `electron-builder --linux`, as per https://github.com/mifi/lossless-cut/blob/189056dfcdec360c9882e4fad8919b3d5c34a404/package.json#L26
Sometimes, though, there are some magic "pre" and "post" scripts involved. That doesn't seem to be the case here, though.

**Comment by mifi** [comment]
yea i think you can run something like `npm exec electron-builder -- --linux -c.asar=false`
