### ISSUE TITLE
 Bug: “LosslessCut is installation is broken”

### ISSUE THREAD

**Issue by 0av** [flathub/no.mifi.losslesscut#20]
Hello,

there is a problem in the Flatpak package of LosslessCut. The error message is:

    LosslessCut is installation is broken
    Command failed with ENOENT: /app/lossless-cut/resources/ffmpeg -hide_banner -f lavfi -i nullsrc=s=256x256:d=1 -f null - spawn /app/lossless-cut/resources/ffmpeg ENOENT

The concerning installed packages are:

    LosslessCut – no.mifi.losslesscut – 3.44.0
    ffmpeg-full – org.freedesktop.Platform.ffmpeg-full – 21.08

**Comment by muelli** [comment]
thanks for reporting.
should be fixed with 99ede7dae619b034b0300b3d4ab4bb476b34c830
