### ISSUE TITLE
No user folders showed

### ISSUE THREAD

**Issue by RafaelLinux** [flathub/no.mifi.losslesscut#34]
I put issue in losslesscut github issues, but they redirect me to here and closed my issue, so here is the issue:
https://github.com/mifi/lossless-cut/issues/1362#issuecomment-1307126939

**Comment by muelli** [comment]
there two aspects to this.

First is that modern Electron can do indeed make use of portals. So once lossless-cut uses a newer Electron, this problem probably goes away. Unfortunately, newer versions of lossless-cut don't build well offline, although I have forgotten the details.

The other aspect is that currently, only a few folders are exposed:
https://github.com/flathub/no.mifi.losslesscut/blob/b72be3591972ab0e9590ba5d36cff126fedbec85/no.mifi.losslesscut.yaml#L14
You can use, e.g., flatseal to expose more folders.

**Comment by RafaelLinux** [comment]
I'm sorry, but I don't understand what do you mean about "flatseal". I'm only a user trying to use Flatpak version of LossLessCut, so I don't know what to do with that information!!!  :(

**Comment by muelli** [comment]
I was referring to this app: https://flathub.org/apps/details/com.github.tchx84.Flatseal
It should help you to configure the permissions you want.

**Comment by RafaelLinux** [comment]
Thank you, I prefer to no install more applications. It's easier to run AppImage version, despite even it doesn't work if I don't use "--no-sandbox" parameter.

**Comment by muelli** [comment]
flatseal is just a fancy UI. You can do everything with "flatpak" yourself, e.g. [flatpak override](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override).

**Comment by RafaelLinux** [comment]
AppImage version is higher than Flatpak version, so I'll give a chance later following your recommendation.

Thank you.
