### ISSUE TITLE
Update flatpak to current version (3.58)

### ISSUE THREAD

**Issue by MMachado05** [flathub/no.mifi.losslesscut#55]
The flatpak version is a few minor versions out-of-date.

**Comment by muelli** [comment]
yeah, would be good to have x-checker-data in the manifest to have newer versions picked up by the bot.

**Comment by caiodev** [comment]
We are already at 3.59.1 as of Jan 2024

https://github.com/mifi/lossless-cut/releases

**Comment by MMachado05** [comment]
Works for me! But yes, some sort of auto-checker to _always_ keep the flatpak up to date would be ideal.
