### ISSUE TITLE
LosslessCut package outdated (3.22.3->3.23.8)

### ISSUE THREAD

**Issue by edmundlaugasson** [flathub/no.mifi.losslesscut#7]
Looks like [Flatpak version of LosslessCut](https://flathub.org/apps/details/no.mifi.losslesscut) is outdated :( [Currently is LosslessCut 3.23.8 out](https://github.com/mifi/lossless-cut/releases), but in Flathub is still 3.22.3... Hopefully it will be in future updated more frequently according program releases.

**Comment by muelli** [comment]
#9
